# Generated by Django 5.1.4 on 2024-12-17 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('niceness_coefficient', models.DecimalField(decimal_places=2, max_digits=3)),
                ('gift', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='SantasList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naughty_list', models.ManyToManyField(related_name='naughty_lists', to='Santa_list.kid')),
                ('nice_list', models.ManyToManyField(related_name='nice_list', to='Santa_list.kid')),
            ],
        ),
    ]
