# Generated by Django 5.1.4 on 2024-12-18 13:50

import toyfactory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toyfactory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toy',
            name='toy_type',
            field=models.CharField(max_length=150, validators=[toyfactory.models.validate_toy_type]),
        ),
    ]
