# Generated by Django 5.1.4 on 2024-12-18 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toyfactory', '0002_alter_toy_toy_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toy',
            name='toy_type',
            field=models.CharField(max_length=150),
        ),
    ]
