# Generated by Django 5.1.4 on 2024-12-18 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('santalist', '0002_alter_santaslist_naughty_list_and_more'),
        ('toyfactory', '0003_alter_toy_toy_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='coal',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='santalist.kid'),
        ),
        migrations.AddField(
            model_name='toy',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='santalist.kid'),
        ),
    ]
