# Generated by Django 5.1.4 on 2024-12-18 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toyfactory', '0004_coal_owner_toy_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='toy',
            name='time_to_make',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
