# Generated by Django 5.1.4 on 2024-12-18 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('santalist', '0002_alter_santaslist_naughty_list_and_more'),
        ('toyfactory', '0005_toy_time_to_make'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coal',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coals', to='santalist.kid'),
        ),
        migrations.AlterField(
            model_name='toy',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='toys', to='santalist.kid'),
        ),
    ]
